### ISSUE TITLE
Redefined/overridden macro when compiling for SAMD21/SAMD51

### ISSUE THREAD

**Issue by agrommek** [sparkfun/SparkFun_DS3234_RTC_Arduino_Library#15]
### Subject of the issue
When compiling sketches for ARM / SAMD Arduinos using this library, the compiler generates a warning:

```
In file included from /home/dummy/Arduino/libraries/SparkFun_DS3234_RTC_Arduino_Library/src/SparkFunDS3234RTC.cpp:24:
/home/dummy/Arduino/libraries/SparkFun_DS3234_RTC_Arduino_Library/src/SparkFunDS3234RTC.h:33: warning: "PM" redefined
   33 | #define PM true
      | 
In file included from /home/dummy/.arduino15/packages/adafruit/tools/CMSIS-Atmel/1.2.2/CMSIS/Device/ATMEL/samd21/include/samd21.h:69,
                 from /home/dummy/.arduino15/packages/adafruit/tools/CMSIS-Atmel/1.2.2/CMSIS/Device/ATMEL/samd.h:105,
                 from /home/dummy/.arduino15/packages/adafruit/tools/CMSIS-Atmel/1.2.2/CMSIS/Device/ATMEL/sam.h:565,
                 from /home/dummy/.arduino15/packages/adafruit/hardware/samd/1.7.5/cores/arduino/Arduino.h:48,
                 from /home/dummy/Arduino/libraries/SparkFun_DS3234_RTC_Arduino_Library/src/SparkFunDS3234RTC.h:23,
                 from /home/dummy/Arduino/libraries/SparkFun_DS3234_RTC_Arduino_Library/src/SparkFunDS3234RTC.cpp:24:
/home/dummy/.arduino15/packages/adafruit/tools/CMSIS-Atmel/1.2.2/CMSIS/Device/ATMEL/samd21/include/samd21g18a.h:476: note: this is the location of the previous definition
  476 | #define PM                ((Pm       *)0x40000400UL) /**< \brief (PM) APB Base Address */
```
### Your workbench
* Arduino IDE 1.8.16
* Adafruit Feather M0 / Adafruit Feather M4 Express (and most probably any other SAMD21 or SAMD51 Arduino)

### Steps to reproduce
* Download the Adafruit board definitions (see here: https://learn.adafruit.com/installing-circuitpython-on-samd21-boards/install-arduino-board-definition)
* Select Board "Adafruit Feather M0" (or any other SAMD-based board like the "classic" Arduino Zero)
* Compile the DS3234 demo sketch

### Expected behavior
No warnings during compilation

### Actual behavior
See warning message above.

### Cause

There is a macro "PM" defined in the header file: https://github.com/sparkfun/SparkFun_DS3234_RTC_Arduino_Library/blob/a82d38acc6fc40ffdb7787d47f0a65a1c0bfa3d5/src/SparkFunDS3234RTC.h#L33

The name "PM" is already defined by the ARM CMSIS framework. As far as I know, PM stand for "Power Manager" and "PM" points to a group of chip registers to control power management functions of the chip (including internal clocks, IMHO). 

I can imagine (but I do not have proof nor example) that re-defining the PM macro may have subtle but unwanted consequences when running on an ARM Arduino. The manual of g++ states, the the new definition overrides the old one:

> If a macro is redefined with a definition that is not effectively the same as the old one, the preprocessor issues a warning and changes the macro to use the new definition.

(From here: https://gcc.gnu.org/onlinedocs/cpp/Undefining-and-Redefining-Macros.html)

### possible solution?

As far as I see, the macros "PM" and "AM" are nowhere used in the DS3234 library. Maybe one could simply remove them or at least rename them? However, this might break existing user code. I don't really know what the best approach would be...

**Comment by nseidle** [comment]
Replicated and I agree - unintended bad things could happen.

There are no examples that call out the bool pm() function but some folks' code may be using `if(rtc.pm() == PM)`. I've renamed the def to DS3234_PM / DS3234_AM. So if this breaks your code (future reader), please use `if(rtc.pm() == DS3234_PM)` instead.

Changing to v1.2 since it's a small backwards break.
