### ISSUE TITLE
DS3234 internal SRAM support functions and Read Alarm1 and 2 values

### ISSUE THREAD

**Issue by Serasidis** [sparkfun/SparkFun_DS3234_RTC_Arduino_Library#2]
Hello and congratulations for this RTC library.
Recently, I designed an alarm clock based on a PCD8544 LCD and the DS3234 RTC chip.
I searched for a library for that RTC chip and I found yours. I saw that two things are missing from the library.
1. Support to the internal 256-byte SRAM that is useful for storing user data to the RTC. 
2. The functions for reading the RTC data from Alarm1 and 2. I wrote two additional functions for that, `void DS3234::getAlarm1(uint8_t *values)` and `void DS3234::getAlarm2(uint8_t *values)` but I don't know if you are interested in these changes.

**Comment by nseidle** [comment]
Sorry it took 5+ years. 

1) I just merged @agrommek PR #13 that supports SRAM read/write.
2) I welcome a PR to add functionality.
