### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Eheran1** [sparkfun/SparkFun_DS3234_RTC_Arduino_Library#3]
Could someone test this library?
The output is broken for me, but its the same with other librarys - but the best working one only has the problem of giving me 1917 as the year instead of 2017, so its not a hardware problem.
Maybe something changed somewhere?
This is some of the (spam) output i get (and why is there no delay(1000) to avoid the spam?):
```
25:165:83 | ÿ - 151/85/65
0:00:04 |  - 0/5/65
20:158:07 |  - 0/0/0
0:00:04 |  - 0/7/158
20:158:07 |  - 0/0/0
0:00:04 |  - 0/7/158
25:165:07 | 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000¡ - 165/165/165
0:00:04 |  - 0/5/65
0:04:07 |  - 0/0/5
0:00:04 |  - 0/5/10
20:158:07 |  - 0/0/0
0:00:04 |  - 0/5/65
ALARM 1!
0:00:00 |  - 0/0/0
0:00:04 |  - 0/0/0
0:00:00 |  - 0/0/0
0:00:04 |  - 0/4/10
25:165:07 |  |  - 165/165/165
0:00:04 |  - 0/5/65
ALARM 1!
20:158:07 |  - 0/0/0
0:00:04 |  - 0/5/67
ALARM 1!
```

Compilation warning:
WARNING: Category 'Sensor' in library SparkFun DS3234 Real-Time Clock (RTC) is not valid. Setting to 'Uncategorized'

**Comment by JoelEB** [comment]
This library works as advertised. The issue is likely a dead or dying coin cell battery.
