### ISSUE TITLE
not reading time - 00.00.00

### ISSUE THREAD

**Issue by ziv1989** [sparkfun/SparkFun_DS3234_RTC_Arduino_Library#4]
Hey!

When I open the serial monitor all i get is this:
0:00:00 |  - 0/0/0

And only once.. so it doesn't continue recording...

I've connected the cs correctly.

Would anyone know of anything else I should check?

**Comment by ziv1989** [comment]
I've also tried changing line:
  rtc.adjust(DateTime(2011, 2, 23, 0, 1, 1));

which doesnt affect anything

**Comment by JoelEB** [comment]
Hi, it may be that the coin cell battery is dead and not retaining an actuate time. Pop it out and measure the voltage with a multimeter to see if it's voltage is around 3V. If not, that could be your problem. If the battery is fine, you'll want to contact our technical support team to further troubleshoot the board.
