### ISSUE TITLE
Re-enabling Alarm 1

### ISSUE THREAD

**Issue by danish-anwar-butt** [sparkfun/SparkFun_DS3234_RTC_Arduino_Library#5]
I'm using ALARM 1 with Arduino UNO interrupt. I want to call ALARM 1 after every 10 seconds.
The issue is that when I re-enable the pin using rtc.setAlarm1(4) in ISR, the INT/SQW  pin remain low and never goes HIGH( the interrupt is not calling again).
here is my code:
`#include <SPI.h>
#include <SparkFunDS3234RTC.h>

// Defining constants
#define RTC_pin 10                                      // RTC chip select pin
#define alarm1_pin 2                                    // Alarm 1 used for reading values
//#define alarm2_pin 3                                    // Alarm 2 used for sleep wake-up

#define a_max_index 4
// we can use internal timer delay for it

// Variables
int s=0;
int alarm_times[] = {10,20,30,40,50};
volatile int a = 0;

// Helper functions

void rtc_init(){
  // assigning pin to RTC object
  rtc.begin(RTC_pin);
  // setting RTC time
  rtc.setTime(0, 0, 0, 0, 0, 0, 0);                    // can use rtc.autoTime(); to set compiler time 
  pinMode(alarm1_pin,INPUT_PULLUP);                    // pull up pin with internal register
  // Configure Alarm(s):
  rtc.enableAlarmInterrupt();                          // (Optional: enable SQW pin as an intterupt) 
  // rtc.setAlarm1(alarm_times[a]);                                    // decide when to read data arguements s,m,h,...
  rtc.setAlarm1(2);
  //rtc.setAlarm2(1);                                    // Decide when to wake-up m,h,...
}

void setup() {
  Serial.begin(9600);
  pinMode(alarm1_pin,INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(alarm1_pin), wu_alarm,FALLING);
  // initialize RTC
  rtc_init();  
}

void loop() {
 
  rtc.update();
  // Read the time:
  s = rtc.second();
  //Serial.println(s);
  delay(500);
}

void wu_alarm(){
  Serial.print("Alarm ");
  Serial.println(alarm_times[a]);

  // check that if index execede then give initial value
  a = a> a_max_index? 0: a++;
  Serial.println(a);
  // re-set alarm
  rtc.setAlarm1(alarm_times[a]);
}
`

**Comment by greiginsydney** [comment]
Hi @danish-anwar-butt. I'm not sure if you've resolved your issue since posting this, but on the off-chance you've not, or for the benefit of anyone following:

The reason the INT/SQW pin remains low is that you're not checking which alarm raised the IRQ, and it remains permanently asserted until you do that, as the process of checking it also resets the alarm.

A call to `if (rtc.alarm1())` will return true if it was Alarm1 that fired, and in so doing also reset the IRQ pin.

Obviously if you're using Alarm2 you'd test that too.

Hope that helps.


\- G.

**Comment by danish-anwar-butt** [comment]
Thanks for your response. I still have the issue and don't know the solution.

**Comment by greiginsydney** [comment]
A few things to try:

First off, clear the alarm in rtc_init() with a call to rtc.alarm1() just after you enable the IRQ. The timer's still running while you're debugging and uploading code and it's quite likely that the alarm is firing "while you're not looking" and remaining asserted until it's cleared. (This one has bitten me before).

I'd also move all of the code out of the interrupt handler (*especially* the Serial.println statements), and just replace it with a flag that you can test for in loop(). The idea is you spend the LEAST time possible in your IRQ handler, using flags to signal back to loop() that it needs to take action.

So in the handler you set a *volatile* "IsAlarmed" bool true, that you then test for in loop(). 

In loop() you'll test if IsAlarm is set, clear the alarm with rtc.alarm1(), and then reset the alarm for the next time. Something like this:
```
if (IsAlarmed == true)
{
  IsAlarmed == false;
  rtc.alarm1();
  //Set the alarm:
  a = a> a_max_index? 0: a++;
  rtc.setAlarm1(alarm_times[a]);
}
```

Strictly speaking though, if you're not doing something else in loop(), you don't need the IRQ. Just read the state of the alarm IRQ pin in loop() and action it when-ever it's low.

\- G.

**Comment by nseidle** [comment]
Closing out stale issues. Please re-open if you have a problem with this library.
